name: Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file
        
      - name: Train model and save artifacts
        run: |
          python trained_model.py  # Replace with your script to train the model
          # Save artifacts to a specific directory
          mkdir -p artifacts
          cp trained_model.pkl artifacts/trained_model.pkl  # Assuming your model is saved as trained_model.pkl

      - name: Build and push Docker image
        env:
          DOCKER_REGISTRY: aimlmodelcontainer.azurecr.io
          IMAGE_NAME: ml-flask-app
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker login $DOCKER_REGISTRY -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trained-model-artifacts
          path: artifacts/
